### ISSUE TITLE
Kanban Board for Ruby Capstone Project

### ISSUE THREAD

**Issue by Ouail-01** [ShiroYaksha90/catalog-of-my-things#25]
This is the link to our Kanban board project for the [ruby-capstone](https://github.com/ShiroYaksha90/catalog-of-my-things/projects/1).

We are a team of 3 people :

👥 Team member 1: @mahabubx7 
👥 Team member 2: @ShiroYaksha90 
👥 Team member 3: @Ouail-01 

Feel free to check out our progress and join us in celebrating our achievements! 🎉

**Comment by cynthiainga** [comment]
Hi @Ouail-01, @ShiroYaksha90 & @mahabubx7, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights

- [ ] Descriptive issue ✔️ 
- [ ] The project link is present ✔️ 
- [ ] The information about the team is present ✔️ 

## Required Changes ♻️

- [ ] Please kindly make sure all your cards have a description, #7, #18, #15, and #5 should have a description 🙃 🙃 
- [ ] You should make sure your different points between you all are not more or less than 5 points, @Ouail-01 has more than 5 points compared to others. Please kindly fix that 🙏🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olamarx** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media4.giphy.com/media/nJKDTpuxnZE7fb6Z1b/giphy.gif"/>
## Highlights
- Fair distribution of tasks ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
